# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: myapi.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='myapi.proto',
  package='myapi',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0bmyapi.proto\x12\x05myapi\"\x17\n\x07request\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x18\n\x05reply\x12\x0f\n\x07message\x18\x01 \x01(\t20\n\x07Greeter\x12%\n\x05sayHi\x12\x0e.myapi.request\x1a\x0c.myapi.replyb\x06proto3')
)




_REQUEST = _descriptor.Descriptor(
  name='request',
  full_name='myapi.request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='myapi.request.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=45,
)


_REPLY = _descriptor.Descriptor(
  name='reply',
  full_name='myapi.reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='myapi.reply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=71,
)

DESCRIPTOR.message_types_by_name['request'] = _REQUEST
DESCRIPTOR.message_types_by_name['reply'] = _REPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

request = _reflection.GeneratedProtocolMessageType('request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'myapi_pb2'
  # @@protoc_insertion_point(class_scope:myapi.request)
  })
_sym_db.RegisterMessage(request)

reply = _reflection.GeneratedProtocolMessageType('reply', (_message.Message,), {
  'DESCRIPTOR' : _REPLY,
  '__module__' : 'myapi_pb2'
  # @@protoc_insertion_point(class_scope:myapi.reply)
  })
_sym_db.RegisterMessage(reply)



_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='myapi.Greeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=73,
  serialized_end=121,
  methods=[
  _descriptor.MethodDescriptor(
    name='sayHi',
    full_name='myapi.Greeter.sayHi',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_REPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
